# Generated by Django 4.1.2 on 2022-10-15 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_bio', models.CharField(max_length=500)),
                ('long_bio', models.TextField(blank=True, null=True)),
                ('years_of_exp', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(default='logo.jpg', upload_to='company/logos')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_on', models.URLField(unique=True)),
                ('member_since', models.DateTimeField(blank=True, null=True)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.advocate')),
            ],
        ),
        migrations.AddField(
            model_name='advocate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
