# Generated by Django 4.1.2 on 2022-10-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', upload_to='advocate/profile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='logo.jpg', upload_to='company/logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sample_photo',
            field=models.ImageField(default='project.jpg', upload_to='projects/'),
        ),
    ]
