# Generated by Django 4.1.2 on 2022-10-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_advocate_profile_pic_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='profile_pic',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='sample_photo',
            field=models.URLField(),
        ),
    ]
