# Generated by Django 4.1.2 on 2022-10-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_account_on_socialaccount_account_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', upload_to='advocate/profile'),
        ),
    ]
